# Generated by Django 4.0.6 on 2022-08-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_order_orderdetail_id_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
    ]
