# Generated by Django 4.0.6 on 2022-09-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_orderdetail_category_id_product_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
