# Generated by Django 4.0.6 on 2022-09-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
