# Generated by Django 4.0.6 on 2022-09-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_orderdetail_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='category_id',
        ),
    ]
